#@ load("@ytt:data", "data")
#@ load("namespace.lib.yml", "getNamespace")
#@ load("deploy.lib.yml", "getDeploy")
#@ load("job.lib.yml", "getJob")
#@ load("cron-job.lib.yml", "getCronJob")
#@ load("service.lib.yml", "getService")
#@ load("ingress.lib.yml", "getIngress")
#@ load("issuer.lib.yml", "getIssuer")
#@ load("volumes.lib.yml", "getVolumeStorages", "getVolumeClaims")
#@ load("conf-map.lib.yml", "getDefaultConfigMap", "getValuesConfigMap")

#@ for project in data.values.projects:
--- #@ getNamespace(project)
#@ if data.values.hasIngress:
--- #@ getIssuer(project)
--- #@ getIngress(project)
#@ end
#@ if data.values.useHttp:
--- #@ getService(project)
#@ end
#@ volumeStorages = getVolumeStorages()
#@ for/end volumeStorage in volumeStorages:
--- #@ volumeStorage
#@ volumeClaims = getVolumeClaims()
#@ for/end volumeClaim in volumeClaims:
--- #@ volumeClaim
#@ if data.values.resourceType == "Deploy":
--- #@ getDeploy(project)
#@ elif data.values.resourceType == "Job":
--- #@ getJob(project)
#@ elif data.values.resourceType == "CronJob":
--- #@ getCronJob(project)
#@ end
--- #@ getDefaultConfigMap(project)
#@ configs = getValuesConfigMap(project)
#@ for/end config in configs:
--- #@ config
#@ end
