#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("utils.star", "utils")
#@ load("job.lib.yml", "getJobSpec")

#@ def getCronJob(project):
apiVersion: batch/v1
kind: CronJob
metadata:
  name: #@ utils.cronJobName()
  labels: #@ utils.defaultLabels("cron-job", project)
  namespace: #@ utils.namespaceName(project)
spec:
  schedule: #@ data.values.schedule
  #@ if/end data.values.cronJobAdditionalConfig:
  _: #@ template.replace(data.values.cronJobAdditionalConfig)
  #@ if/end data.values.cronJobAdditionalConfigByEnvironment and data.values.cronJobAdditionalConfigByEnvironment[data.values.environment]:
  _: #@ template.replace(data.values.cronJobAdditionalConfigByEnvironment[data.values.environment])
  jobTemplate:
    metadata:
      labels: #@ utils.defaultLabels("job", project)
    spec: #@ getJobSpec(project)
#@ end