#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("utils.star", "utils")
#@ load("deploy.lib.yml", "getPodSpec")

#@ def getJobSpec(project):
#@ if/end data.values.jobAdditionalConfig:
_: #@ template.replace(data.values.jobAdditionalConfig)
#@ if/end data.values.jobAdditionalConfigByEnvironment and data.values.jobAdditionalConfigByEnvironment[data.values.environment]:
_: #@ template.replace(data.values.jobAdditionalConfigByEnvironment[data.values.environment])
template: #@ getPodSpec(project)
#@ end

#@ def getJob(project):
apiVersion: batch/v1
kind: Job
metadata:
  name: #@ utils.jobName()
  labels: #@ utils.defaultLabels("job", project)
  namespace: #@ utils.namespaceName(project)
spec: #@ getJobSpec(project)
#@ end